@TmsApi_HostAddress = http://localhost:5196

GET {{TmsApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TmsApi_HostAddress}}/api/enrollments/worker-smoke
Accept: application/json

###

curl http://localhost:5196/api/enrollments

###

curl -X POST http://localhost:5196/api/enrollments \
-H "Content-Type: application/json" \
-d '{"studentId":"S-001","courseCode":"CS-101"}'

###


curl http://localhost:5196/api/enrollments/ab865c54

###

curl -X DELETE http://localhost:5196/api/enrollments/ab865c54

###

curl http://localhost:5196/api/enrollments/ab865c54

###

curl http://localhost:5196/api/error

###

