@TmsApi_HostAddress = http://localhost:5196

GET {{TmsApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TmsApi_HostAddress}}/api/enrollments/worker-smoke
Accept: application/json

###

curl http://localhost:5196/api/enrollments

###

curl -X POST http://localhost:5196/api/enrollments \
-H "Content-Type: application/json" \
-d '{"studentId":"S-001","courseCode":"CS-101"}'

###


curl http://localhost:5196/api/enrollments/ab865c54

###

curl -X DELETE http://localhost:5196/api/enrollments/ab865c54

###

curl http://localhost:5196/api/enrollments/ab865c54

###

curl http://localhost:5196/api/error

###

curl http://localhost:5196/api/students

###

curl -X POST http://localhost:5196/api/students \
-H "Content-Type: application/json" \
-d '{"studentId":"S-001","courseCode":"CS-101"}'

###


curl http://localhost:5196/api/students/{id}

###

curl -X DELETE http://localhost:5196/api/students/{id}

###

curl http://localhost:5196/api/students/{id}

###

curl http://localhost:5196/api/courses

###

curl -X POST http://localhost:5196/api/courses \
-H "Content-Type: application/json" \
-d '{"studentId":"S-001","courseCode":"CS-101"}'

###


curl http://localhost:5196/api/courses/{courseCode}

###

curl -X DELETE http://localhost:5196/api/courses/{courseCode}

###

curl http://localhost:5196/api/courses/{courseCode}
###

curl http://localhost:5196/api/test/deferred

###

curl http://localhost:5196/api/test/translation-fail

###

curl -X DELETE http://localhost:5196/api/reports/students/1

###
curl http://localhost:5196/api/reports/students

###

curl http://localhost:5196/api/reports/students/all

###

curl -X POST http://localhost:5196/api/reports/archive-old-enrollments

###

curl http://localhost:5196/api/courses/2

###
curl http://localhost:5196/api/courses

###